Support custom suffix for resources
atc-net/atc-azure-options pull request #12
Opened 2021-12-01 17:57 UTC by lupusbytes

This PR adds an overload to `INamingProvider.GetResourceName` to support custom suffixes for resources.
Some projects need multiple resources of the same type. In this case, a suffix can be used to identify resources and resolve name clashes.
Other projects may simply have a standard where the resource type abbreviation is appended to the resource.

2021-12-01 18:00 UTC, lupusbytes commented
While we are on this subject, should we also consider supporting prefixes ? 
I personally don't have any need for this, but I think it's worth considering the extra flexibility.
Code wise it would be a minimal addition, just like this PR is.

2021-12-01 18:09 UTC, lupusbytes commented
Also I would like your opinion on if this should optional parameter(s) or overload(s)

2021-12-02 07:03 UTC, kimlundjohansen commented
Prefixes sounds fine to me. Regarding overloads vs optional parameter. Since there is no default for suffix, I would prefer overload.

2021-12-02 07:04 UTC, kimlundjohansen approved these changes

2021-12-02 07:28 UTC, cjakobsen commented
> Prefixes sounds fine to me. Regarding overloads vs optional parameter. Since there is no default for suffix, I would prefer overload.

Agree

2021-12-02 07:32 UTC, cjakobsen requested changes

2021-12-02 07:32 UTC, cjakobsen commented on src/Atc.Azure.Options/Providers/NamingProvider.cs
> +            => GetResourceName(options, namingOptions, suffix: string.Empty);
No need for this, if it was an optional parameter it would make sense.

2021-12-02 09:32 UTC, cjakobsen approved these changes

2021-12-02 09:32 UTC, merged